/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as WithnavbarImport } from './routes/_with_navbar'
import { Route as IndexImport } from './routes/index'
import { Route as WithnavbarSettingsImport } from './routes/_with_navbar/settings'
import { Route as WithnavbarAnkiConnectSetupImport } from './routes/_with_navbar/anki-connect-setup'
import { Route as WithnavbarAboutImport } from './routes/_with_navbar/about'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const WithnavbarRoute = WithnavbarImport.update({
  id: '/_with_navbar',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WithnavbarSettingsRoute = WithnavbarSettingsImport.update({
  path: '/settings',
  getParentRoute: () => WithnavbarRoute,
} as any)

const WithnavbarAnkiConnectSetupRoute = WithnavbarAnkiConnectSetupImport.update(
  {
    path: '/anki-connect-setup',
    getParentRoute: () => WithnavbarRoute,
  } as any,
)

const WithnavbarAboutRoute = WithnavbarAboutImport.update({
  path: '/about',
  getParentRoute: () => WithnavbarRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_with_navbar': {
      preLoaderRoute: typeof WithnavbarImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/_with_navbar/about': {
      preLoaderRoute: typeof WithnavbarAboutImport
      parentRoute: typeof WithnavbarImport
    }
    '/_with_navbar/anki-connect-setup': {
      preLoaderRoute: typeof WithnavbarAnkiConnectSetupImport
      parentRoute: typeof WithnavbarImport
    }
    '/_with_navbar/settings': {
      preLoaderRoute: typeof WithnavbarSettingsImport
      parentRoute: typeof WithnavbarImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  WithnavbarRoute.addChildren([
    WithnavbarAboutRoute,
    WithnavbarAnkiConnectSetupRoute,
    WithnavbarSettingsRoute,
  ]),
  OnboardingRoute,
])

/* prettier-ignore-end */
